### ISSUE TITLE
PRNG should provide a method telling which RNG is used

### ISSUE THREAD

**Issue by yoannkubera** [gildasmorvan/similar#2]
__Issue witnessed in commit:__  52c5843

## Issue description

The `PRNG` class from the extended libs was recently added a method to change the seed being used. Yet, as long as the implementation of the RNG is unknown to the user, simulations are not guaranteed to be reproducible, since the default RNG of `PRNG` might be changed in the future from _XORO_ to _Xoshiro256StarStar_.

Therefore, `PRNG` should include a method telling which RNG is used in a readable format and, to facilitate simulation reproduction, a method loading such a RNG.

## Issue location

Similar extended libs, class `PRNG` of package `fr.univ_artois.lgi2a.similar.extendedkernel.libs.random`

## Possible solutions

1. __Make `get` method public__
    The most simple (an probably most unsuitable) method should be to switch the private static `get( )` method to public, to grant access to the class instance of `Random`.

1. __Create an export/import RNG feature__
    Ideally, PRNG should provide two methods `export():String` and `import(String)` providing the expected facilitators:
    * The `export` method should convert the current RNG instance (`instance` static attribute) to a readable String containing all the relevant information for its construction. in practice, it probably will delegate the work to a method from the RNG class (maybe `toString()` ?)
    * The `import` method should parse a String obtained through `export` and convert it to a usable RNG instance. In practice, it probably delegate part of the work to an RNG constructor having a String argument, or to an `initialize(String)` method.

**Comment by yoannkubera** [comment]
My bad, it probably won't be changed from XORO to Xoshiro256StarStar in the short term.
Though, my point stays valid :)

**Comment by gildasmorvan** [comment]
Add a `getImplementationName` method in PRNG that returns the name of the class that implements the RNG.
